language: python
dist: xenial
python:
  - "3.9"

stages:
  - lint
  - test
  - name: deploy
    if: branch = main

before_install:
  - sudo apt-get update
  - sudo apt-get -y install tesseract-ocr
  - tesseract --help
  - pip install poetry==1.1.12

install:
  - poetry install

jobs:
  include:
    - stage: lint
      script: 
      - poetry run lint
      - poetry run bandit
    - stage: test
      script:
      - poetry run coverage
      - poetry run unit_tests
    - stage: deploy
      script:
        - echo "Deploying to PyPI..."
