language: python
dist: xenial
python:
  - "3.9"

services:
  - docker

stages:
  - lint
  - test
  - build
  - name: deploy
    if: branch = main

before_install:
  - sudo apt-get update
  - sudo apt-get -y install tesseract-ocr
  - sudo cat /etc/ImageMagick-6/policy.xml | tail
  - sudo sed -i 's/<policy domain="coder" rights="none" pattern="PDF" \/>/<policy domain="coder" rights="read|write" pattern="PDF" \/>/g' /etc/ImageMagick-6/policy.xml
  - sudo cat /etc/ImageMagick-6/policy.xml | tail
  - tesseract --help
  - pip install poetry

install:
  - poetry install

jobs:
  include:
    - stage: lint
      script: 
      - poetry run lint
      - poetry run bandit
    - stage: test
      script:
      - poetry run coverage
      - poetry run unit_tests
    - stage: build
      script:
        - docker build -t bra/backend:latest .
    - stage: deploy
      script:
        - echo "docker push ..."
