language: python
dist: focal
python:
  - "3.9"

services:
  - docker

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

stages:
  - test
  - build
  - name: deploy
    if: branch = main

before_install:
  - sudo apt-get update
  - sudo apt-get -y install tesseract-ocr
  - sudo cat /etc/ImageMagick-6/policy.xml | tail
  - sudo sed -i 's/<policy domain="coder" rights="none" pattern="PDF" \/>/<policy domain="coder" rights="read|write" pattern="PDF" \/>/g' /etc/ImageMagick-6/policy.xml
  - sudo cat /etc/ImageMagick-6/policy.xml | tail
  - tesseract --help
  - pip install poetry


jobs:
  include:
    - stage: test
      install: poetry install
      script: 
      - poetry run lint
      - poetry run bandit
      - poetry run coverage
      - poetry run unit_tests
    - stage: build
      install: skip
      script:
        - docker build -t bra/backend:latest .
    - stage: deploy
      before_install: skip
      install: skip
      script:
        - bash deploy.sh
