# cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: bra-database
spec:
  schedule: "0 23 * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 10
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: bra-database
            image: gcr.io/data-baguette/bra-database:latest
            envFrom:
            - secretRef:
                name: bra-db-creds
            resources:
              requests:
                memory: "512Mi"
                cpu: "500m"
                ephemeral-storage: "256Mi"
              limits:
                memory: "1Gi"
                cpu: "500m"
                ephemeral-storage: "500Mi"
          restartPolicy: Never
